### ISSUE TITLE
Create a "collaborate" redirect for the site

### ISSUE THREAD

**Issue by joesepi** [instructlab/website#107]
Create a redirect to go to collaboration page

https://instructlab.ai/collaborate =>
github collaboration documentation

**Comment by mariat189** [comment]
Hi @joesepi ,
I'm interested in contributing to this project and would like to work on this issue. Please let me know if I can take on this issue or if there's anything else I should be aware of before I start.

**Comment by Lo-Mein** [comment]
Hi @joesepi @mariat189, I am also interested in contributing to this project and thought this would be a good first issue. Is this still being worked on, or does it still need to be done? Thank you

**Comment by mariat189** [comment]
Hi @Lo-Mein , 
I am currently working on this.
