### ISSUE TITLE
"Join the community" button touches the bottom footer of the website

### ISSUE THREAD

**Issue by oindrillac** [instructlab/website#34]
### What are we seeing?

On Safari and Chrome the vertical space at the bottom of the last section before above the footer has disappeared. "Join the community" button touches the footer now, was that an intended change?

![image](https://github.com/instructlab/website/assets/32435206/b4d81b83-2cc1-470f-a7e6-9750735a1d28)

### Intended behavior

"Join the community" button does not touch the footer, there is some vertical whitespace

**Comment by wking** [comment]
Related to screen width?

![image](https://github.com/instructlab/website/assets/209920/0af2ece1-a2a4-4289-a514-51fe89f38019)

![image](https://github.com/instructlab/website/assets/209920/b8ac0930-c2f1-4834-bdd4-c0da56b8dc5d)

![image](https://github.com/instructlab/website/assets/209920/28cdc100-f2ed-4925-9604-efcbff2ac492)

**Comment by joesepi** [comment]
Thanks @wking and @oindrillac for catching this. I'm not sure what exactly is going on because I am unable to test on a Linux box (assuming this is on Linux as I am not seeing this on my Mac) but I added some margin-top to the footer in #35 

We may need to simply deploy it to see if the fix works. :)

**Comment by wking** [comment]
I don't see it in mobile-emulation mode, which is surprising if it is actually a window-width issue:

![image](https://github.com/instructlab/website/assets/209920/7692d1db-c958-422a-87da-1348ae2a90d6)

**Comment by wking** [comment]
Maybe this helps?

![image](https://github.com/instructlab/website/assets/209920/05bff81c-3499-4009-9b8e-e4031021e8f3)

**Comment by wking** [comment]
Looks  good to me with #35; thanks!

![image](https://github.com/instructlab/website/assets/209920/ccf4b569-5eeb-4a7e-b5d0-0374c1603d9f)
