### ISSUE TITLE
InfographicAnimation is broken

### ISSUE THREAD

**Issue by RobotSail** [instructlab/website#53]
The `InfographicAnimation` components that activate 1-by-1 as the user progresses down the page are currently broken. Attempts to scroll through will cause the animation boxes to glitch and fail to transition from one into another.

**Comment by lhawthorn** [comment]
@joesepi is this something you can fix? If not and we need help from our sysadmin team, LMK.

In general, we should work on updating the website but given the ever growing backlog we can prioritize that in 2048. :laughing:
